In [1]:
import pandas as pd
import numpy as np

La dataframe Pandas est la représentation en mémoire des données la plus utilisée en Data Science avec Python. Que vous travaillez avec des données temporelles, des données provenant des BDD SQL, des données du web, des fichiers textes, excels, des API (Application Programming Interface), la maîtrise de Pandas est absolument essentielle pour vous car c'est un puissant outil qui vous facilitera la vie.             
A travers ce cours, vous apprendrez les fondamentaux de Pandas pour l'importation et l'analyse des données.

In [2]:
un_panda_numpy = np.array([100, 5, 20, 80])
un_panda_numpy

array([100,   5,  20,  80])

Ici, notre panda a des pattes de 100cm, des poils de 5cm en moyenne, une queue de 20cm et un ventre de 80cm de diamètre.


Si on veut représenter plusieurs pandas, on crée une liste de tableaux numpy


In [5]:
# Famille pandas

famille_panda =[
    [100, 5, 20, 80], #maman
    [50, 2.5, 10, 40], #bébé
    [110, 6, 22, 80] #papa
]

famille_panda_numpy = np.array(famille_panda)
famille_panda_numpy

array([[100. ,   5. ,  20. ,  80. ],
       [ 50. ,   2.5,  10. ,  40. ],
       [110. ,   6. ,  22. ,  80. ]])

Par exemple, supposons qu'on veuille obtenir la taille des pattes (situé en position 0 dans chaque liste qui décrit un panda) du panda situé en position 2 dans ma liste (c'est-à-dire papa panda).

In [15]:
# taille des pattes de papa panda, à la manière numpy
famille_panda_numpy[2,0]

110.0

Pour connaître les tailles des pattes de toute la famille panda :


In [23]:
# le contenu de la premiere colonne
famille_panda_numpy[:,0]

array([100.,  50., 110.])